### ISSUE TITLE
Add Harbor workflow

### ISSUE THREAD

**Issue by jdolitsky** [bloodorangeio/oci-distribution-conformance-results#9]
Create GitHub action at `.github/workflows/harbor.yml` that does the following:

- Starts up a harbor test environment
- Runs the [OCI Conformance tests](https://github.com/opencontainers/distribution-spec/tree/master/conformance)
- Uploads report.html

Need to also add related details and badge to the readme under "goharbor/harbor"

**Comment by jdolitsky** [comment]
Example workflow:

```
name: zot
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-zot
  schedule:
    - cron: '0 6 * * *'
jobs:
  run:
    services:
      zot:
        image: quay.io/bloodorange/zot:9ecb5ce
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: http://zot:5000
          OCI_NAMESPACE: bloodorange/oci-conformance-test
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/zot.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
